//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Component
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int id { get; set; }
        public int Userid { get; set; }
        public int ClothesId { get; set; }
        public int NumberId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> IsTaken { get; set; }
    
        public virtual Clothes Clothes { get; set; }
        public virtual Number Number { get; set; }
        public virtual User User { get; set; }
    }
}
