//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeAdmin.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes
    {
        public int id { get; set; }
        public int TypeId { get; set; }
        public int ColourId { get; set; }
        public string Size { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Collor Collor { get; set; }
        public virtual Type Type { get; set; }
        public virtual User User { get; set; }
    }
}
